name: Build COMMON and publish to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    env:
      USER: GHA-Workflow
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  publish:
    name: Publish distribution to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/project/emod-common
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
